### ISSUE TITLE
Installation via npm error

### ISSUE THREAD

**Issue by tadowns** [Festify/cordova-spotify#21]
Recently I was developing with an older copy of this repo that i pulled down locally and was referencing. Today decided to try installing via the recent npm release and am receiving an error:

`Running command:pathtostuff/plugins/cordova-spotify/package.sh
        pathtoApp
        Failed to install 'cordova-spotify': Error: spawn EACCES
        at exports._errnoException (util.js:1026:11)
        at ChildProcess.spawn (internal/child_process.js:313:11)
        at Object.exports.spawn (child_process.js:385:9)
        at Object.exports.spawn
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/superspawn.js:134:31)
        at runScriptViaChildProcessSpawn
        (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:226:23)
        at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:167:16)
        at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
        at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
        at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
        at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
        Error: spawn EACCES
`

**Comment by tadowns** [comment]
Just tested using the:

ionic cordova plugin add https://github.com/Festify/cordova-spotify

instead of ionic cordova plugin add cordova-spotify
and it works fine

**Comment by mraerino** [comment]
Thanks for reporting this 🙂
Sounds like a execution permission problem in the NPM module.
We will either fix this or finally migrate the shell script to a js script (for better Win compat).

**Comment by Remco75** [comment]
any update on this? I still get errors, even with the suggestion of @tadowns.

I get this error when doing `ionic cordova plugin add https://github.com/Festify/cordova-spotify`


FAILURE: Build failed with an exception.

        * Where:
        Build file '/Users/remco/me-love-radio/plugins/cordova-spotify/src/android/spotify-auth/auth-lib/build.gradle'
        line: 73

        * What went wrong:
        A problem occurred evaluating project ':auth-lib'.
        > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME
        environment variable.

**Comment by Remco75** [comment]
never mind. My android home was not set properly.

**Comment by NeoLegends** [comment]
Closing because of inactivity and #31. Feel free to reopen :)
