### ISSUE TITLE
Failed to install cordova-spotify: Cordova-error: Uh oh!

### ISSUE THREAD

**Issue by eduardoewgo** [Festify/cordova-spotify#45]
When trying to build the phonegap app through the cloud build service I am getting this error:

PLUGIN OUTPUT
--------------------------------------------------------------------------------
"plugman-151 install --platform android --project /project --plugin cordova-spotify --nohooks=.": Fetching plugin "cordova-spotify" via npm
Installing "cordova-spotify" at "0.5.8" for android
Fetching plugin "es6-promise-plugin" via npm
Installing "es6-promise-plugin" at "4.2.2" for android
Error during processing of action! Attempting to revert...
**Failed to install 'cordova-spotify': CordovaError: Uh oh!**
"/project/cordova/plugins/cordova-spotify/src/android/spotify-sdk/spotify-player-24-noconnect-2.20b.aar" not found!
    at copyFile (/project/cordova/lib/pluginHandlers.js:219:36)
    at install (/project/cordova/lib/pluginHandlers.js:74:13)
    at Object.process (/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/project/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/project/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at /project/cordova/Api.js:254:18
    at _fulfilled (/project/cordova/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/project/cordova/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/project/cordova/node_modules/q/q.js:796:13)
    at /project/cordova/node_modules/q/q.js:556:49
Uh oh!
**"/project/cordova/plugins/cordova-spotify/src/android/spotify-sdk/spotify-player-24-noconnect-2.20b.aar" not found!**

Any help?

I would send the versions of node, npm and cordova, but since it is the cloud that is compiling I am not sure how can I check those versions.

**Comment by NeoLegends** [comment]
Hmm, I'm kinda wondering whats happening here. When I download the archive file the plugin is downloading during installation, `spotify-player-24-noconnect-2.20b.aar` is present.

**Comment by ArpitMakvana** [comment]
the same problem with me also
